import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { cp, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const manifest = JSON.parse(await readFile(join(root, "package.json"), "utf8"));
const name = `${manifest.name}-${manifest.version}`;
const output = join(root, "dist");
await mkdir(output, { recursive: true });

function run(command, args, cwd = root) {
	const result = spawnSync(command, args, { cwd, encoding: "utf8" });
	if (result.error || result.status !== 0) throw new Error(result.stderr || `${command} failed`);
	return result.stdout;
}

run("npm", ["pack", "--ignore-scripts", "--json", "--pack-destination", output]);
const staging = await mkdtemp(join(tmpdir(), "ds-maxpower-pack-"));
try {
	run("tar", ["-xzf", join(output, `${name}.tgz`), "-C", staging]);
	await cp(join(staging, "package"), join(staging, name), { recursive: true });
	const zip = join(output, `${name}.zip`);
	// This exact file is generated by this script; rebuilding must not retain old zip entries.
	await rm(zip, { force: true });
	run("zip", ["-q", "-r", "-X", zip, name], staging);
	const sums = await Promise.all(
		[`${name}.tgz`, `${name}.zip`].map(async (file) => {
			const hash = createHash("sha256")
				.update(await readFile(join(output, file)))
				.digest("hex");
			return `${hash}  ${file}`;
		}),
	);
	await writeFile(join(output, "SHA256SUMS"), `${sums.join("\n")}\n`);
	console.log(sums.join("\n"));
} finally {
	await rm(staging, { recursive: true, force: true });
}
